### ISSUE TITLE
Diseño figma pagina web

### ISSUE THREAD

**Issue by Joaco2603** [javatlacati/temachpedia#50]
**¿Su sugerencia está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ej. Siempre me siento frustrado cuando [...]

**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.

**Describe las alternativas que hayas considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

**Contexto adicional**
Agregue aquí cualquier otro contexto o capturas de pantalla sobre la solicitud de función.

**Comment by javatlacati** [comment]
favor de llenar los campos o este isue se cerrará

**Comment by javatlacati** [comment]
cerrado por falta de información
