### ISSUE TITLE
Cambio de estilo en el readme

### ISSUE THREAD

**Issue by angelcruz07** [javatlacati/temachpedia#60]
**¿Su sugerencia está relacionada con un problema? Por favor describa.**
Mi sigerencia se basa en mejorar el estilo del readme y como este se ve de manera visual en el repositorio del proyecto

**Describe la solución que te gustaría**
Agregar estilos propios de markdown asi como de html agregando un poco de dinamismo y color a la documentacion del proyecto 

**Describe las alternativas que hayas considerado**
Considero agregar a los contrubuidores del proyecto en una seccion especializada del readme 

**Contexto adicional**
SIn contexto adicional

**Comment by javatlacati** [comment]
favor de estructurar la historia de usuario de manera apropiada, tel como está escrita no hay manera de verificar el valor aportado.  Al respecto se puede leer https://www.atlassian.com/es/agile/project-management/user-stories
