### ISSUE TITLE
FEAT: Add Linters (Eslint, Prettier, Lint-Staged) with pre-commit lint (Husky)

### ISSUE THREAD

**Issue by Juanestban** [javatlacati/temachpedia#68]
## **¿Su sugerencia está relacionada con un problema? Por favor describa.**
cuando desarrollamos un repositorio siempre se tienen equipos con diferentes configuraciones en sus `IDLE` (vscode) por lo que se tendran muchas formas de progrmar en javascript sin un estandar por el cual regirse y tener un estandar para cada formateada que se tenga en el codigo

## **Describe la solución que te gustaría**
Agregar
- Eslint
- Pretter
- eslint-config-prettier
- configurar prettier y eslint
- agregar ignore files de eslint y prettier
- usar el husky para tener pipe donde se pueda correr un comando para lintar el codigo que se hizo antes de hacer un commit de los cambios
- agregar el lint-staged para poder correr 2 comandos donde se usa el `eslint` y `prettier` durante la ejecucion del precommit

## **Describe las alternativas que hayas considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

## **Contexto adicional**
Se pueden usar tambien plugins del vscode para facilitar tambien el formateado del codigo y el filtrado de errores detectados con el eslint

### Error Lens
![image](https://github.com/javatlacati/temachpedia/assets/53704567/965d80f8-ef4a-4128-8f93-ab6d232457a0)

### Prettier
![image](https://github.com/javatlacati/temachpedia/assets/53704567/3ed3fa6b-3f6e-4a87-8cbc-eecb208ca44a)

### Eslint
![image](https://github.com/javatlacati/temachpedia/assets/53704567/969f6905-cc85-41c5-bef1-21c66af2530e)

### Prettier Eslint
![image](https://github.com/javatlacati/temachpedia/assets/53704567/44294dc1-16f5-4ff0-9859-2b8f1e849cc9)

**Comment by javatlacati** [comment]
Excelente, en caso de que alguien pregunte por qué no usar TSLint, su uso fue deprecado por los desarrolladores de angular.
